### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by reiz** [max-power/ping-pong#1]
@max-power Under which license is this software? MIT?

**Comment by max-power** [comment]
I don't consider it enough to put a license on. Do whatever you like with it.

**Comment by reiz** [comment]
@max-power then you should take the "Do What the Fuck You Want to Public License": http://www.wtfpl.net/ :-) 

With a license you are communicating how other people can use your code. If you don't have a license many people will not use your project because there is a risk that you come up with a proprietary license afterwards. If you don't care then just use the WTFPL ;-)

**Comment by max-power** [comment]
Merged. Thanks.
